/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-04-18 07:04:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/main/../include/footer.jsp", Long.valueOf(1681265952000L));
    _jspx_dependants.put("/WEB-INF/views/main/../include/bHeader.jsp", Long.valueOf(1681266024000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1681799246000L));
    _jspx_dependants.put("jar:file:/D:/work3/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/team/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/work3/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/team/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"utf-8\" dir=\"ltr\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"utf-8\" dir=\"ltr\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <!--  \r\n");
      out.write("    JavaScripts\r\n");
      out.write("    =============================================\r\n");
      out.write("    -->\r\n");
      out.write("    <script src=\"assets/lib/jquery/dist/jquery.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/bootstrap/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/wow/dist/wow.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/jquery.mb.ytplayer/dist/jquery.mb.YTPlayer.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/isotope/dist/isotope.pkgd.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/imagesloaded/imagesloaded.pkgd.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/flexslider/jquery.flexslider.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/owl.carousel/dist/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/smoothscroll.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/magnific-popup/dist/jquery.magnific-popup.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/simple-text-rotator/jquery.simple-text-rotator.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/plugins.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/main.js\"></script>   \r\n");
      out.write("    \r\n");
      out.write("    <!--  \r\n");
      out.write("    Document Title\r\n");
      out.write("    =============================================\r\n");
      out.write("    -->\r\n");
      out.write("    <title>Perro</title>\r\n");
      out.write("    <!--  \r\n");
      out.write("    Favicons\r\n");
      out.write("    =============================================\r\n");
      out.write("    -->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"assets/images/favicons/apple-icon-57x57.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"assets/images/favicons/apple-icon-60x60.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"assets/images/favicons/apple-icon-72x72.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"assets/images/favicons/apple-icon-76x76.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"assets/images/favicons/apple-icon-114x114.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"assets/images/favicons/apple-icon-120x120.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"assets/images/favicons/apple-icon-144x144.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"assets/images/favicons/apple-icon-152x152.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"assets/images/favicons/apple-icon-180x180.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"192x192\" href=\"assets/images/favicons/android-icon-192x192.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"assets/images/favicons/favicon-32x32.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"96x96\" href=\"assets/images/favicons/favicon-96x96.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"assets/images/favicons/favicon-16x16.png\">\r\n");
      out.write("    <link rel=\"manifest\" href=\"/manifest.json\">\r\n");
      out.write("    <meta name=\"msapplication-TileColor\" content=\"#ffffff\">\r\n");
      out.write("    <meta name=\"msapplication-TileImage\" content=\"assets/images/favicons/ms-icon-144x144.png\">\r\n");
      out.write("    <meta name=\"theme-color\" content=\"#ffffff\">\r\n");
      out.write("    <!--  \r\n");
      out.write("    Stylesheets\r\n");
      out.write("    =============================================\r\n");
      out.write("    \r\n");
      out.write("    -->\r\n");
      out.write("    <!-- Default stylesheets-->\r\n");
      out.write("    <link href=\"assets/lib/bootstrap/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Template specific stylesheets-->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Volkhov:400i\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/animate.css/animate.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/components-font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/et-line-font/et-line-font.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/flexslider/flexslider.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/owl.carousel/dist/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/owl.carousel/dist/assets/owl.theme.default.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/magnific-popup/dist/magnific-popup.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/simple-text-rotator/simpletextrotator.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Main stylesheet and color file-->\r\n");
      out.write("    <link href=\"assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link id=\"color-scheme\" href=\"assets/css/colors/default.css\" rel=\"stylesheet\">\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <body data-spy=\"scroll\" data-target=\".onpage-navigation\" data-offset=\"60\">\r\n");
      out.write("    <main>\r\n");
      out.write("      <div class=\"page-loader\">\r\n");
      out.write("        <div class=\"loader\">Loading...</div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <nav class=\"navbar navbar-custom navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"navbar-header\">\r\n");
      out.write("            <button class=\"navbar-toggle\" type=\"button\" data-toggle=\"collapse\" data-target=\"#custom-collapse\">\r\n");
      out.write("            <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("            <span class=\"icon-bar\"></span><span class=\"icon-bar\">\r\n");
      out.write("            </span><span class=\"icon-bar\"></span></button>\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"index.html\">Perro</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"collapse navbar-collapse\" id=\"custom-collapse\">\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("            \r\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Home</a>\r\n");
      out.write("                <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("                \r\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">About</a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                      <li><a href=\"about_choi\">code</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                 \r\n");
      out.write("                  \r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              \r\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Service</a>\r\n");
      out.write("                <ul class=\"dropdown-menu\">\r\n");
      out.write("                  \r\n");
      out.write("                  <li><a href=\"reservation_home\"><i class=\"fa fa-check-square-o\"></i> reservation</a></li>\r\n");
      out.write("                  <li><a href=\"javascript:idCheck2()\">Reserv Cancel</a></li>\r\n");
      out.write("                  \r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">shop</a>\r\n");
      out.write("                <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">product</a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                      <li><a href=\"product_All\">All</a></li>\r\n");
      out.write("                      <li><a href=\"product_Cno_List?cno=1\">Clothes</a></li>\r\n");
      out.write("                      <li><a href=\"product_Cno_List?cno=2\">Toy</a></li>\r\n");
      out.write("                      <li><a href=\"product_Cno_List?cno=3\">Snack</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              \r\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">FaQ</a>\r\n");
      out.write("                <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("                  <li><a href=\"faq_Home\"><i class=\"fa fa-server\"></i> FaQ</a></li>\r\n");
      out.write("                  <li><a href=\"javascript:idCheck()\"><i class=\"fa fa-font\"></i> q&a</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("                  ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                  <li class=\"d-inline-block d-md-none ml-md-0\"><a href=\"#\" class=\"site-menu-toggle js-menu-toggle\"><span class=\"icon-menu\"></span></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("\r\n");
      out.write(" <input type=\"hidden\" name=\"mid\" id=\"mid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginUser.mid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write(" \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function idCheck(){\r\n");
      out.write("    if(document.getElementById(\"mid\").value == \"\") {\r\n");
      out.write("    	alert(\"로그인이 필요합니다.\");\r\n");
      out.write("   		return false;\r\n");
      out.write("    }else{\r\n");
      out.write("        var link = 'qna_Home?mid='+document.getElementById(\"mid\").value;\r\n");
      out.write("        location.href=link;\r\n");
      out.write("    }\r\n");
      out.write("    }\r\n");
      out.write("	\r\n");
      out.write("	function idCheck2(){\r\n");
      out.write("	    if(document.getElementById(\"mid\").value == \"\") {\r\n");
      out.write("	    	alert(\"로그인이 필요합니다.\");\r\n");
      out.write("	   		return false;\r\n");
      out.write("	    }else{\r\n");
      out.write("	        var link = 'NowreservationListAll?mid='+document.getElementById(\"mid\").value;\r\n");
      out.write("	        location.href=link;\r\n");
      out.write("	    }\r\n");
      out.write("	    }\r\n");
      out.write("</script>      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      ");
      out.write("\n");
      out.write("</head>    \n");
      out.write("<body>\n");
      out.write("      <section class=\"home-section home-parallax home-fade home-full-height bg-dark-30\" id=\"home\" data-background=\"img/dog01.jpg\">\n");
      out.write("        <div class=\"titan-caption\">\n");
      out.write("          <div class=\"caption-content\">\n");
      out.write("            <div class=\"font-alt mb-30 titan-title-size-1\">Hello &amp; welcome</div>\n");
      out.write("            <div class=\"font-alt mb-40 titan-title-size-4\">We are Perro</div>\n");
      out.write("            <a class=\"section-scroll btn btn-border-w btn-round\" href=\"#about\">Learn More</a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </section>\n");
      out.write("      \n");
      out.write("      <div class=\"main\">\n");
      out.write("        <section class=\"module\" id=\"about\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("            \n");
      out.write("              <div class=\"col-sm-8 col-sm-offset-2\">\n");
      out.write("                <h2 class=\"module-title font-alt\">Welcome to Perro</h2>\n");
      out.write("               		<div class=\"module-subtitle font-serif large-text\">\n");
      out.write("                      위 사이트는 이젠아카데미 <br>자바(JAVA) 스프링프레임워크 개발자 양성과정<br>\n");
      out.write("                      (2022-11-09 ~ 2023-04-12) <br>\n");
      out.write("                      최진관,이수민의 애견미용샵을 주제로한 졸업 작품 입니다\n");
      out.write("					</div>\n");
      out.write("              </div>\n");
      out.write("              \n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-sm-2 col-sm-offset-5\">\n");
      out.write("                <div class=\"large-text align-center\"><a class=\"section-scroll\" href=\"#services\"><i class=\"fa fa-angle-down\"></i></a></div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </section>\n");
      out.write("        <hr class=\"divider-w\">\n");
      out.write("        \n");
      out.write("        <section class=\"module\" id=\"services\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-sm-6 col-sm-offset-3\">\n");
      out.write("                <h2 class=\"module-title font-alt\">Our Skills</h2>\n");
      out.write("                <div class=\"module-subtitle font-serif\">\"We used [insert programming language] to create our website <br>\n");
      out.write("                and we feel confident in our ability to handle this technology.\"</div>\n");
      out.write("              </div>\n");
      out.write("                 \n");
      out.write("              <div class=\"row\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row multi-columns-row\">\n");
      out.write("              <div class=\"col-md-3 col-sm-6 col-xs-12\">\n");
      out.write("                <div class=\"features-item\">\n");
      out.write("                  <div class=\"features-icon\"><span class=\"icon-desktop\"></span></div>\n");
      out.write("                  <h3 class=\"features-title font-alt\">Java</h3>\n");
      out.write("                  \n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-md-3 col-sm-6 col-xs-12\">\n");
      out.write("                <div class=\"features-item\">\n");
      out.write("                  <div class=\"features-icon\"><span class=\"icon-tablet\"></span></div>\n");
      out.write("                  <h3 class=\"features-title font-alt\">Spring Framework</h3>\n");
      out.write("                  \n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-md-3 col-sm-6 col-xs-12\">\n");
      out.write("                <div class=\"features-item\">\n");
      out.write("                  <div class=\"features-icon\"><span class=\"icon-laptop\"></span></div>\n");
      out.write("                  <h3 class=\"features-title font-alt\">HTML</h3>\n");
      out.write("                  \n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-md-3 col-sm-6 col-xs-12\">\n");
      out.write("                <div class=\"features-item\">\n");
      out.write("                  <div class=\"features-icon\"><span class=\"icon-paperclip\"></span></div>\n");
      out.write("                  <h3 class=\"features-title font-alt\">GitHub</h3>\n");
      out.write("                  \n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-md-3 col-sm-6 col-xs-12\">\n");
      out.write("                <div class=\"features-item\">\n");
      out.write("                  <div class=\"features-icon\"><span class=\"icon-linegraph\"></span></div>\n");
      out.write("                  <h3 class=\"features-title font-alt\">Apache Tomcat</h3>\n");
      out.write("                  \n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-md-3 col-sm-6 col-xs-12\">\n");
      out.write("                <div class=\"features-item\">\n");
      out.write("                  <div class=\"features-icon\"><span class=\"icon-genius\"></span></div>\n");
      out.write("                  <h3 class=\"features-title font-alt\">AJAX</h3>\n");
      out.write("                  \n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-md-3 col-sm-6 col-xs-12\">\n");
      out.write("                <div class=\"features-item\">\n");
      out.write("                  <div class=\"features-icon\"><span class=\"icon-tools-2\"></span></div>\n");
      out.write("                  <h3 class=\"features-title font-alt\">JSP</h3>\n");
      out.write("                  \n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-md-3 col-sm-6 col-xs-12\">\n");
      out.write("                <div class=\"features-item\">\n");
      out.write("                  <div class=\"features-icon\"><span class=\"icon-upload\"></span></div>\n");
      out.write("                  <h3 class=\"features-title font-alt\">AWS</h3>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              \n");
      out.write("               <div class=\"row\">\n");
      out.write("              <div class=\"col-sm-2 col-sm-offset-5\">\n");
      out.write("                <div class=\"large-text align-center\"><a class=\"section-scroll\" href=\"#skill\"><i class=\"fa fa-angle-down\"></i></a></div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            </div>\n");
      out.write("              \n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </section>\n");
      out.write("    \n");
      out.write("        <hr class=\"divider-w\" id=\"skill\">\n");
      out.write("        <section class=\"module\" id=\"team\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-sm-6 col-sm-offset-3\">\n");
      out.write("                <h2 class=\"module-title font-alt\">Meet Our Team</h2>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\" >\n");
      out.write("              <div class=\"mb-sm-20 wow fadeInUp col-sm-offset-3 col-md-3\" onclick=\"wow fadeInUp\">\n");
      out.write("                <div class=\"team-item\">\n");
      out.write("                  <div class=\"team-image\"><img src=\"assets/images/Beagle.jpg\" alt=\"Member Photo\"/>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"team-descr font-alt\">\n");
      out.write("                    <div class=\"team-name\">JinGwan Choi</div>\n");
      out.write("                    <div class=\"team-role\">\"Future developer\"</div>\n");
      out.write("                      <div class=\"team-role\" style=\"text-transform:lowercase;\">\"gkrjrjrj@naver.com\"</div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"mb-sm-20 wow fadeInUp col-md-3\">\n");
      out.write("                <div class=\"team-item\">\n");
      out.write("                  <div class=\"team-image\"><img src=\"assets/images/Maltese.jpg\" alt=\"Member Photo\"/> \n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"team-descr font-alt\">\n");
      out.write("                    <div class=\"team-name\">SuMin LEE</div>\n");
      out.write("                    <div class=\"team-role\">\"Future developer\"</div>\n");
      out.write("                    <div class=\"team-role\" style=\"text-transform:lowercase;\">\"dltnals5449@naver.com\"</div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </section>\n");
      out.write("       \n");
      out.write("        <hr class=\"divider-d\">\n");
      out.write("        </div>\n");
      out.write("</body>    \n");
      out.write("\r\n");
      out.write("<!-- Footer Start -->\r\n");
      out.write("  <hr class=\"divider-d\">\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("        <hr class=\"divider-d\">\r\n");
      out.write("        <footer class=\"footer bg-dark\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-sm-6\">\r\n");
      out.write("                <p class=\"copyright font-alt\">&copy; 2023&nbsp;<a href=\"index.html\">TitaN</a>, All Rights Reserved</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-sm-6\">\r\n");
      out.write("                <div class=\"footer-social-links\"><a href=\"#\"><i class=\"fa fa-facebook\"></i></a><a href=\"#\"><i class=\"fa fa-twitter\"></i></a><a href=\"#\"><i class=\"fa fa-dribbble\"></i></a><a href=\"#\"><i class=\"fa fa-skype\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("      <div class=\"scroll-up\"><a href=\"#totop\"><i class=\"fa fa-angle-double-up\"></i></a></div>\r\n");
      out.write("</html>");
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("					");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("					");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/main/../include/bHeader.jsp(147,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginUser==null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<li><a href=\"login\"><i class=\"fa fa-lock\"></i> Login</a></li>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/main/../include/bHeader.jsp(150,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginUser.aposition==1 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<li><a href=\"admin_home\"><i class=\"fa fa-lock\"></i> Admin</a></li>\r\n");
          out.write("						<li><a href=\"logout\"><i class=\"fa fa-unlock\"></i> Logout</a></li>\r\n");
          out.write("						<li><a href=\"reservationListAll\"><span class=\"icon icon-person\"></span> Mypage</a></li>\r\n");
          out.write("						<li><a href=\"cartlist\"><span class=\"icon icon-shopping_cart\"></span> Cart</a></li>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<li><a href=\"logout\"><i class=\"fa fa-unlock\"></i> logout</a></li>\r\n");
          out.write("						<li><a href=\"reservationListAll\"><span class=\"icon icon-person\"></span> Mypage</a></li>\r\n");
          out.write("						<li><a href=\"cartlist\"><span class=\"icon icon-shopping_cart\"></span> Cart</a></li>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
