/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-04-18 07:08:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/main/../include/footer.jsp", Long.valueOf(1681265952000L));
    _jspx_dependants.put("/WEB-INF/views/main/../include/bHeader.jsp", Long.valueOf(1681266024000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1681799246000L));
    _jspx_dependants.put("jar:file:/D:/work3/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/team/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/work3/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/team/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"utf-8\" dir=\"ltr\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <!--  \r\n");
      out.write("    JavaScripts\r\n");
      out.write("    =============================================\r\n");
      out.write("    -->\r\n");
      out.write("    <script src=\"assets/lib/jquery/dist/jquery.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/bootstrap/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/wow/dist/wow.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/jquery.mb.ytplayer/dist/jquery.mb.YTPlayer.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/isotope/dist/isotope.pkgd.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/imagesloaded/imagesloaded.pkgd.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/flexslider/jquery.flexslider.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/owl.carousel/dist/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/smoothscroll.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/magnific-popup/dist/jquery.magnific-popup.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/simple-text-rotator/jquery.simple-text-rotator.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/plugins.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/main.js\"></script>   \r\n");
      out.write("    \r\n");
      out.write("    <!--  \r\n");
      out.write("    Document Title\r\n");
      out.write("    =============================================\r\n");
      out.write("    -->\r\n");
      out.write("    <title>Perro</title>\r\n");
      out.write("    <!--  \r\n");
      out.write("    Favicons\r\n");
      out.write("    =============================================\r\n");
      out.write("    -->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"assets/images/favicons/apple-icon-57x57.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"assets/images/favicons/apple-icon-60x60.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"assets/images/favicons/apple-icon-72x72.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"assets/images/favicons/apple-icon-76x76.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"assets/images/favicons/apple-icon-114x114.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"assets/images/favicons/apple-icon-120x120.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"assets/images/favicons/apple-icon-144x144.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"assets/images/favicons/apple-icon-152x152.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"assets/images/favicons/apple-icon-180x180.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"192x192\" href=\"assets/images/favicons/android-icon-192x192.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"assets/images/favicons/favicon-32x32.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"96x96\" href=\"assets/images/favicons/favicon-96x96.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"assets/images/favicons/favicon-16x16.png\">\r\n");
      out.write("    <link rel=\"manifest\" href=\"/manifest.json\">\r\n");
      out.write("    <meta name=\"msapplication-TileColor\" content=\"#ffffff\">\r\n");
      out.write("    <meta name=\"msapplication-TileImage\" content=\"assets/images/favicons/ms-icon-144x144.png\">\r\n");
      out.write("    <meta name=\"theme-color\" content=\"#ffffff\">\r\n");
      out.write("    <!--  \r\n");
      out.write("    Stylesheets\r\n");
      out.write("    =============================================\r\n");
      out.write("    \r\n");
      out.write("    -->\r\n");
      out.write("    <!-- Default stylesheets-->\r\n");
      out.write("    <link href=\"assets/lib/bootstrap/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Template specific stylesheets-->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Volkhov:400i\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/animate.css/animate.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/components-font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/et-line-font/et-line-font.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/flexslider/flexslider.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/owl.carousel/dist/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/owl.carousel/dist/assets/owl.theme.default.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/magnific-popup/dist/magnific-popup.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/simple-text-rotator/simpletextrotator.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Main stylesheet and color file-->\r\n");
      out.write("    <link href=\"assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link id=\"color-scheme\" href=\"assets/css/colors/default.css\" rel=\"stylesheet\">\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <body data-spy=\"scroll\" data-target=\".onpage-navigation\" data-offset=\"60\">\r\n");
      out.write("    <main>\r\n");
      out.write("      <div class=\"page-loader\">\r\n");
      out.write("        <div class=\"loader\">Loading...</div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <nav class=\"navbar navbar-custom navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"navbar-header\">\r\n");
      out.write("            <button class=\"navbar-toggle\" type=\"button\" data-toggle=\"collapse\" data-target=\"#custom-collapse\">\r\n");
      out.write("            <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("            <span class=\"icon-bar\"></span><span class=\"icon-bar\">\r\n");
      out.write("            </span><span class=\"icon-bar\"></span></button>\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"index.html\">Perro</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"collapse navbar-collapse\" id=\"custom-collapse\">\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("            \r\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Home</a>\r\n");
      out.write("                <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("                \r\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">About</a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                      <li><a href=\"about_choi\">code</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                 \r\n");
      out.write("                  \r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              \r\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Service</a>\r\n");
      out.write("                <ul class=\"dropdown-menu\">\r\n");
      out.write("                  \r\n");
      out.write("                  <li><a href=\"reservation_home\"><i class=\"fa fa-check-square-o\"></i> reservation</a></li>\r\n");
      out.write("                  <li><a href=\"javascript:idCheck2()\">Reserv Cancel</a></li>\r\n");
      out.write("                  \r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">shop</a>\r\n");
      out.write("                <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">product</a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                      <li><a href=\"product_All\">All</a></li>\r\n");
      out.write("                      <li><a href=\"product_Cno_List?cno=1\">Clothes</a></li>\r\n");
      out.write("                      <li><a href=\"product_Cno_List?cno=2\">Toy</a></li>\r\n");
      out.write("                      <li><a href=\"product_Cno_List?cno=3\">Snack</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              \r\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">FaQ</a>\r\n");
      out.write("                <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("                  <li><a href=\"faq_Home\"><i class=\"fa fa-server\"></i> FaQ</a></li>\r\n");
      out.write("                  <li><a href=\"javascript:idCheck()\"><i class=\"fa fa-font\"></i> q&a</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("                  ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                  <li class=\"d-inline-block d-md-none ml-md-0\"><a href=\"#\" class=\"site-menu-toggle js-menu-toggle\"><span class=\"icon-menu\"></span></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("\r\n");
      out.write(" <input type=\"hidden\" name=\"mid\" id=\"mid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginUser.mid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write(" \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function idCheck(){\r\n");
      out.write("    if(document.getElementById(\"mid\").value == \"\") {\r\n");
      out.write("    	alert(\"로그인이 필요합니다.\");\r\n");
      out.write("   		return false;\r\n");
      out.write("    }else{\r\n");
      out.write("        var link = 'qna_Home?mid='+document.getElementById(\"mid\").value;\r\n");
      out.write("        location.href=link;\r\n");
      out.write("    }\r\n");
      out.write("    }\r\n");
      out.write("	\r\n");
      out.write("	function idCheck2(){\r\n");
      out.write("	    if(document.getElementById(\"mid\").value == \"\") {\r\n");
      out.write("	    	alert(\"로그인이 필요합니다.\");\r\n");
      out.write("	   		return false;\r\n");
      out.write("	    }else{\r\n");
      out.write("	        var link = 'NowreservationListAll?mid='+document.getElementById(\"mid\").value;\r\n");
      out.write("	        location.href=link;\r\n");
      out.write("	    }\r\n");
      out.write("	    }\r\n");
      out.write("</script>      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	  <div class=\"main\">\r\n");
      out.write("             <section class=\"module bg-dark-30\" data-background=\"img/login01.jpg\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-sm-6 col-sm-offset-3\">\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        \r\n");
      out.write("        <section class=\"module\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("             \r\n");
      out.write("               <div class=\"col-sm-5 col-sm-offset-3 mb-sm-40\"\r\n");
      out.write("              style=\"border: 1px solid #c8c8c8; border-radius: 1em; background-color:white;\">\r\n");
      out.write("                <h3 class=\"font-alt\">회원가입</h3>\r\n");
      out.write("                <hr class=\"divider-w mb-10\">\r\n");
      out.write("               <form class=\"user\" name=\"joinForm\" id=\"joinForm\" method=\"post\"\r\n");
      out.write("			action=\"joinOk\">\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                 		<input type=\"text\" class=\"form-control\"\r\n");
      out.write("										id=\"mid2\" placeholder=\"아이디\" name=\"mid2\" onchange=\"check_id()\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <input class=\"form-control\" id=\"mname\" type=\"text\" name=\"mname\" placeholder=\"이름\"/>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <input class=\"form-control\" id=\"mpwd\" type=\"password\" name=\"mpwd\" placeholder=\"비밀번호\"/>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <input class=\"form-control\" id=\"rpwd\" type=\"password\" name=\"rpwd\" placeholder=\"비밀번호확인\"/>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <input class=\"form-control\" id=\"mphone\" type=\"text\" name=\"mphone\" placeholder=\"전화번호(000-0000-0000)\"/>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"sr-only\" for=\"address\">주소</label>\r\n");
      out.write("                    <input type=\"text\" id=\"sample6_address\" onclick=\"sample6_execDaumPostcode()\" class=\"form-control\" placeholder=\"주소찾기(클릭하시오)*\" required=\"required\" data-validation-required-message=\"Please enter your maddr.\"\r\n");
      out.write("								name=\"addr1\"> \r\n");
      out.write("								<input type=\"hidden\" id=\"sample6_address1\" \r\n");
      out.write("								name=\"sample6_address1\" placeholder=\"주소\">\r\n");
      out.write("								<br>\r\n");
      out.write("								<input type=\"hidden\" id=\"sample6_postcode\" \r\n");
      out.write("								name=\"sample6_postcode\" placeholder=\"우편번호\" >\r\n");
      out.write("\r\n");
      out.write("								<input type=\"hidden\" id=\"sample6_extraAddress\"\r\n");
      out.write("								name=\"sample6_extraAddress\" placeholder=\"참고항목\">\r\n");
      out.write("								<input type=\"text\" id=\"sample6_address2\" class=\"form-control\" placeholder=\"상세주소*\"  required=\"required\" data-validation-required-message=\"Please enter your maddr.\"\r\n");
      out.write("								placeholder=\"상세주소\" name=\"sample6_address2\" size=\"50\"\r\n");
      out.write("								onchange=\"addrdd()\" >\r\n");
      out.write("								<input type=\"hidden\" id=\"maddr\" name=\"maddr\" readonly=\"readonly\" size=50>\r\n");
      out.write("								 <p class=\"help-block text-danger\"></p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <input class=\"form-control\" id=\"email\" type=\"email\" name=\"email\" placeholder=\"이메일\" onblur=\"check_id()\" required=\"required\" data-validation-required-message=\"Please enter your email.\"/>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  \r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                   <a href=\"javascript:joinOk()\"\r\n");
      out.write("									class=\"btn btn-block btn-round btn-b\"> 가입하기 </a>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </form>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </section>\r\n");
      out.write("	</div>\r\n");
      out.write("	</body>\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	function check_id() {\r\n");
      out.write("		var mid = document.getElementById(\"mid2\");\r\n");
      out.write("		var idcheck = /^(?=.*[a-zA-Z])(?=.*[0-9]).{8,12}$/.test(document\r\n");
      out.write("				.getElementById(\"mid2\").value); //영문,숫자\r\n");
      out.write("\r\n");
      out.write("		if (mid.value == \"\") {\r\n");
      out.write("			alert(\"아이디를 입력해 주세요\");\r\n");
      out.write("			mid.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if (!idcheck) {\r\n");
      out.write("			alert(\"아이디는 영문,숫자,특수문자 조합이어야합니다 8~12자\");\r\n");
      out.write("			document.getElementById(\"mid2\").value = null;\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		$\r\n");
      out.write("				.ajax({\r\n");
      out.write("					type : \"POST\",\r\n");
      out.write("					url : \"idCheck\",\r\n");
      out.write("					dataType : \"text\",\r\n");
      out.write("					data : {\r\n");
      out.write("						\"mid2\" : mid.value\r\n");
      out.write("					},\r\n");
      out.write("					contentType : 'application/x-www-form-urlencoded; charset=utf-8',\r\n");
      out.write("					success : function(result) {\r\n");
      out.write("						if (result == \"success\") {\r\n");
      out.write("							alert(\"사용가능한 아이디 입니다.\");\r\n");
      out.write("							ok=0;\r\n");
      out.write("						} else {\r\n");
      out.write("							alert(\"이미사용중인 아이디 입니다.\");\r\n");
      out.write("							document.getElementById(\"mid2\").value = null;\r\n");
      out.write("							ok = 1;\r\n");
      out.write("							\r\n");
      out.write("						}\r\n");
      out.write("					},\r\n");
      out.write("					error : function() {\r\n");
      out.write("						alert(\"아이디 체크가 실패하였습니다.\");\r\n");
      out.write("\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("	}\r\n");
      out.write("	  function sample6_execDaumPostcode() {\r\n");
      out.write("			new daum.Postcode(\r\n");
      out.write("					{\r\n");
      out.write("						oncomplete : function(data) {\r\n");
      out.write("							// 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("							// 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("							// 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("							var addr = ''; // 주소 변수\r\n");
      out.write("							var extraAddr = ''; // 참고항목 변수\r\n");
      out.write("\r\n");
      out.write("							//사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("							if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("								addr = data.roadAddress;\r\n");
      out.write("							} else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("								addr = data.jibunAddress;\r\n");
      out.write("							}\r\n");
      out.write("\r\n");
      out.write("							// 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.\r\n");
      out.write("							if (data.userSelectedType === 'R') {\r\n");
      out.write("								// 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("								// 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("								if (data.bname !== ''\r\n");
      out.write("										&& /[동|로|가]$/g.test(data.bname)) {\r\n");
      out.write("									extraAddr += data.bname;\r\n");
      out.write("								}\r\n");
      out.write("								// 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("								if (data.buildingName !== ''\r\n");
      out.write("										&& data.apartment === 'Y') {\r\n");
      out.write("									extraAddr += (extraAddr !== '' ? ', '\r\n");
      out.write("											+ data.buildingName : data.buildingName);\r\n");
      out.write("								}\r\n");
      out.write("								// 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("								if (extraAddr !== '') {\r\n");
      out.write("									extraAddr = ' (' + extraAddr + ')';\r\n");
      out.write("								}\r\n");
      out.write("								// 조합된 참고항목을 해당 필드에 넣는다.\r\n");
      out.write("								document.getElementById(\"sample6_extraAddress\").value = extraAddr;\r\n");
      out.write("\r\n");
      out.write("							} else {\r\n");
      out.write("								document.getElementById(\"sample6_extraAddress\").value = '';\r\n");
      out.write("							}\r\n");
      out.write("\r\n");
      out.write("							// 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("							document.getElementById('sample6_postcode').value = data.zonecode;\r\n");
      out.write("							document.getElementById(\"sample6_address\").value = addr;\r\n");
      out.write("							// 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("							document.getElementById(\"sample6_address2\")\r\n");
      out.write("									.focus();\r\n");
      out.write("						}\r\n");
      out.write("					}).open();\r\n");
      out.write("		}\r\n");
      out.write("	  \r\n");
      out.write("	  function addrdd() {\r\n");
      out.write("		  var addr1 = \"우편번호:\"+document.getElementById(\"sample6_postcode\").value+\"  주소:\";\r\n");
      out.write("		  var addr2 = document.getElementById(\"sample6_address\").value;\r\n");
      out.write("		  var addr3 = document.getElementById(\"sample6_extraAddress\").value+\"  \";\r\n");
      out.write("		  var addr4 = document.getElementById(\"sample6_address2\").value;\r\n");
      out.write("\r\n");
      out.write("		  document.getElementById(\"maddr\").value = addr1+addr2+addr3+addr4;\r\n");
      out.write("		  \r\n");
      out.write("		  }\r\n");
      out.write("	function joinOk() {\r\n");
      out.write("\r\n");
      out.write("		var phone = document.getElementById(\"mphone\").value;\r\n");
      out.write("		var idcheck = /^(?=.*[a-zA-Z])(?=.*[0-9]).{8,12}$/.test(document\r\n");
      out.write("				.getElementById(\"mid2\").value); //영문,숫자\r\n");
      out.write("		var check1 = /^(?=.*[a-zA-Z])(?=.*[0-9]).{8,12}$/.test(document\r\n");
      out.write("				.getElementById(\"mpwd\").value); //영문,숫자\r\n");
      out.write("		var check2 = /^(?=.*[a-zA-Z])(?=.*[^a-zA-Z0-9]).{8,12}$/\r\n");
      out.write("				.test(document.getElementById(\"mpwd\").value); //영문,특수문자\r\n");
      out.write("		var check3 = /^(?=.*[^a-zA-Z0-9])(?=.*[0-9]).{8,12}$/.test(document\r\n");
      out.write("				.getElementById(\"mpwd\").value); //특수문자, 숫자\r\n");
      out.write("\r\n");
      out.write("		if (document.getElementById(\"mid2\").value == \"\") {\r\n");
      out.write("			alert(\"아이디를 입력해 주세요\");\r\n");
      out.write("			document.getElementById(\"mid2\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if (!(check1 || check2 || check3)) {\r\n");
      out.write("			alert(\"비밀번호는 영문,숫자,특수문자 조합이어야합니다 8~12자\");\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		if (/(\\w)\\1\\1/.test(document.getElementById(\"mpwd\").value)) {\r\n");
      out.write("			alert(\"같은 문자를 3번 이상 사용하실 수 없습니다.\\n패스워드 설정안내를 확인해 주세요.\");\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		if (document.getElementById(\"mname\").value == \"\") {\r\n");
      out.write("			alert(\"이름을 입력해 주세요\");\r\n");
      out.write("			document.getElementById(\"mname\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		if (document.getElementById(\"mpwd\").value == \"\") {\r\n");
      out.write("			alert(\"비밀번호를 입력해 주세요\");\r\n");
      out.write("			document.getElementById(\"mpwd\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		if (document.getElementById(\"rpwd\").value == \"\") {\r\n");
      out.write("			alert(\"비밀번호확인을 입력해 주세요\");\r\n");
      out.write("			document.getElementById(\"rpwd\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if (document.getElementById(\"rpwd\").value != document\r\n");
      out.write("				.getElementById(\"mpwd\").value) {\r\n");
      out.write("			alert(\"비밀번호가 일치하지 않습니다\");\r\n");
      out.write("			document.getElementById(\"rpwd\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if (phone == \"\") {\r\n");
      out.write("			alert(\"연락처를 입력해 주세요\");\r\n");
      out.write("			document.getElementById(\"mphone\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("\r\n");
      out.write("		} else if (!(/^[0-9]{3}-[0-9]{4}-[0-9]{4}$/.test(phone))) {\r\n");
      out.write("			alert(\"제대로 입력해주세요(000-0000-0000)\");\r\n");
      out.write("			document.getElementById(\"mphone\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if (document.getElementById(\"maddr\").value == \"\") {\r\n");
      out.write("			alert(\"주소를 입력해 주세요\");\r\n");
      out.write("			document.getElementById(\"maddr\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		} \r\n");
      out.write("		alert(\"회원가입완료\");\r\n");
      out.write("		var form = document.getElementById('joinForm');\r\n");
      out.write("		form.action = \"joinOk\";\r\n");
      out.write("		form.submit();\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!-- Footer Start -->\r\n");
      out.write("  <hr class=\"divider-d\">\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("        <hr class=\"divider-d\">\r\n");
      out.write("        <footer class=\"footer bg-dark\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-sm-6\">\r\n");
      out.write("                <p class=\"copyright font-alt\">&copy; 2023&nbsp;<a href=\"index.html\">TitaN</a>, All Rights Reserved</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-sm-6\">\r\n");
      out.write("                <div class=\"footer-social-links\"><a href=\"#\"><i class=\"fa fa-facebook\"></i></a><a href=\"#\"><i class=\"fa fa-twitter\"></i></a><a href=\"#\"><i class=\"fa fa-dribbble\"></i></a><a href=\"#\"><i class=\"fa fa-skype\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("      <div class=\"scroll-up\"><a href=\"#totop\"><i class=\"fa fa-angle-double-up\"></i></a></div>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("					");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("					");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/main/../include/bHeader.jsp(147,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginUser==null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<li><a href=\"login\"><i class=\"fa fa-lock\"></i> Login</a></li>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/main/../include/bHeader.jsp(150,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginUser.aposition==1 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<li><a href=\"admin_home\"><i class=\"fa fa-lock\"></i> Admin</a></li>\r\n");
          out.write("						<li><a href=\"logout\"><i class=\"fa fa-unlock\"></i> Logout</a></li>\r\n");
          out.write("						<li><a href=\"reservationListAll\"><span class=\"icon icon-person\"></span> Mypage</a></li>\r\n");
          out.write("						<li><a href=\"cartlist\"><span class=\"icon icon-shopping_cart\"></span> Cart</a></li>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<li><a href=\"logout\"><i class=\"fa fa-unlock\"></i> logout</a></li>\r\n");
          out.write("						<li><a href=\"reservationListAll\"><span class=\"icon icon-person\"></span> Mypage</a></li>\r\n");
          out.write("						<li><a href=\"cartlist\"><span class=\"icon icon-shopping_cart\"></span> Cart</a></li>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
